name = "memorial-api"
compatibility_date = "2025-07-21"
main = "worker.js"
type = "javascript"

account_id = ""


[vars]
SUPABASE_URL = "https://.supabase.co"
SUPABASE_ANON_KEY = ""

[env.production]
workers_dev = true
